# Generated by Django 5.2.1 on 2025-07-14 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSubmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicSubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniSubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='department_images/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EndowmentPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('founder', models.CharField(max_length=255)),
                ('memory_of', models.CharField(max_length=255)),
                ('awarded_to', models.TextField()),
                ('amount', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExtensionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='studentdesk/forms/')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='HomepageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HomeQuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text="Use Bootstrap icon class (e.g., 'bi-bank')", max_length=50)),
                ('link', models.CharField(blank=True, help_text='Enter internal (e.g., /placement/) or full URL', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NAACSubmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RankHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('paper', models.CharField(default='Part III (Major)', max_length=100)),
                ('rank', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='rankholders/')),
            ],
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/')),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDeskMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('table_html', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='about/pdfs/')),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='homepage.aboutsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('table_html', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='academic/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='academic/pdfs/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.academicsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('table_html', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='activities/files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/images/')),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='homepage.activitysubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='AlumniContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('table_html', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='alumni/files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='alumni/images/')),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='homepage.alumnisubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('about', 'About'), ('faculty', 'Faculty'), ('association', 'Association'), ('syllabus', 'Syllabus'), ('gallery', 'Gallery'), ('achievements', 'Achievements'), ('intercollege', 'Intercollege Meet'), ('vision', 'Vision Mission')], max_length=50)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('table_html', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='departments/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='departments/pdfs/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.department')),
            ],
        ),
        migrations.CreateModel(
            name='ExtensionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('table_html', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='extension/images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='extension/files/')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.extensioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='faculty/photos/')),
                ('cv_pdf', models.FileField(blank=True, null=True, upload_to='faculty/cv/')),
                ('position', models.CharField(blank=True, max_length=200)),
                ('qualifications', models.CharField(blank=True, max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.department')),
            ],
        ),
        migrations.CreateModel(
            name='NAACContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='naac/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='naac/pdfs/')),
                ('table_html', models.TextField(blank=True)),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.naacsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('UG', 'UG'), ('PG', 'PG')], default='UG', max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('eligibility', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, help_text='Which department takes care of this course?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.department')),
            ],
            options={
                'ordering': ['level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('photo', models.ImageField(blank=True, upload_to='staff_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDeskContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('table_html', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='studentdesk/files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='studentdesk/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='studentdesk/videos/')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='homepage.studentdeskmenu')),
            ],
        ),
    ]
