# Generated by Django 5.2.1 on 2025-06-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('main_image', models.ImageField(upload_to='main_images/')),
            ],
        ),
    ]
