# Generated by Django 5.2.1 on 2025-06-19 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSubmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicSubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='main_images/')),
            ],
        ),
        migrations.CreateModel(
            name='NAACSubmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDeskMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('table_html', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='about/pdfs/')),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='homepage.aboutsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='academic/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='academic/pdfs/')),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.academicsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='homepage.activitysection')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('block', models.TextField(blank=True)),
                ('table_html', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='activity_pdfs/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='homepage.activitysection')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('about', 'About'), ('faculty', 'Faculty'), ('association', 'Association'), ('syllabus', 'Syllabus'), ('gallery', 'Gallery'), ('achievements', 'Achievements'), ('intercollege', 'Intercollege Meet')], max_length=50)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='departments/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='departments/pdfs/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.department')),
            ],
        ),
        migrations.CreateModel(
            name='NAACContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='naac/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='naac/pdfs/')),
                ('table_html', models.TextField(blank=True)),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.naacsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDeskContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('table_html', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='studentdesk/files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='studentdesk/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='studentdesk/videos/')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='homepage.studentdeskmenu')),
            ],
        ),
    ]
