# Generated by Django 5.2.1 on 2025-07-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='activitysubmenu',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='extensioncategory',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='activitysubmenu',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extensioncategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activitycontentblock',
            name='heading',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
