# Generated by Django 5.2.1 on 2025-07-15 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_sportssection_alter_activitysubmenu_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitycontentblock',
            name='submenu',
        ),
        migrations.RemoveField(
            model_name='alumnicontentblock',
            name='submenu',
        ),
        migrations.RemoveField(
            model_name='extensioncontent',
            name='extension',
        ),
        migrations.DeleteModel(
            name='SportsSection',
        ),
        migrations.DeleteModel(
            name='ActivityContentBlock',
        ),
        migrations.DeleteModel(
            name='ActivitySubMenu',
        ),
        migrations.DeleteModel(
            name='AlumniContentBlock',
        ),
        migrations.DeleteModel(
            name='AlumniSubMenu',
        ),
        migrations.DeleteModel(
            name='ExtensionCategory',
        ),
        migrations.DeleteModel(
            name='ExtensionContent',
        ),
    ]
