# Generated by Django 5.2.1 on 2025-06-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_sliderimage_remove_homepagecontent_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeQuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text="Use Bootstrap icon class (e.g., 'bi-bank')", max_length=50)),
                ('link', models.URLField(blank=True, help_text='Optional: Add link to internal/external page')),
            ],
        ),
    ]
