# Generated by Django 5.2.1 on 2025-06-07 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_aboutsection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutSection',
            new_name='AboutMenu',
        ),
    ]
