# Generated by Django 5.2.1 on 2025-06-22 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_homequicklink'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeQuickLinkBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('paragraph', models.TextField(blank=True)),
                ('icon', models.CharField(help_text='Eg: bi-bank, bi-camera-video', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quicklinks/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='quicklinks/pdfs/')),
                ('table_html', models.TextField(blank=True, help_text='Paste <table> HTML code')),
                ('link', models.URLField(blank=True, help_text='Optional link for heading', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HomeQuickLinkSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='HomeQuickLink',
        ),
        migrations.AddField(
            model_name='homequicklinkblock',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='homepage.homequicklinksection'),
        ),
    ]
