# Generated by Django 5.2.1 on 2025-06-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_academicmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicmenu',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='academicmenu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='academic/menu_images/'),
        ),
        migrations.AddField(
            model_name='academicmenu',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='academic/menu_pdfs/'),
        ),
    ]
