# Generated by Django 5.2.1 on 2025-07-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_activitysubmenu_event_extensionsection_extensionunit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('administrative', 'Administrative Staff'), ('menial', 'Menials')], max_length=20)),
            ],
            options={
                'verbose_name': 'Administrative',
                'verbose_name_plural': 'Administrative',
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='magazines/pdfs/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='magazines/covers/')),
            ],
            options={
                'verbose_name': 'Magazine',
                'verbose_name_plural': 'Magazines',
            },
        ),
    ]
