# Generated by Django 5.2.1 on 2025-07-16 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_administrative_magazine'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='homepage.sportssection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SportsFacilityContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sports/facilities/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='sports/facilities_pdfs/')),
                ('table_html', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='homepage.sportsfacility')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
