# Generated by Django 5.2.1 on 2025-06-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_homequicklink_delete_homequicklinkblock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homequicklink',
            name='link',
            field=models.CharField(blank=True, help_text='Enter internal (e.g., /placement/) or full URL', max_length=200),
        ),
    ]
