# Generated by Django 5.2.1 on 2025-07-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_sportsfacility_sportsfacilitycontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsfacilitycontent',
            name='facility',
        ),
        migrations.DeleteModel(
            name='SportsFacility',
        ),
        migrations.DeleteModel(
            name='SportsFacilityContent',
        ),
    ]
