# Generated by Django 5.2.1 on 2025-06-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_academiccalendar_faculty_organizedevent_outcome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='academic_images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='academic_pdfs/')),
            ],
        ),
        migrations.DeleteModel(
            name='AcademicCalendar',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='OrganizedEvent',
        ),
        migrations.DeleteModel(
            name='Outcome',
        ),
        migrations.DeleteModel(
            name='Programmer',
        ),
    ]
