# Generated by Django 5.2.1 on 2025-07-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_remove_sportsfacilitycontent_facility_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrative',
            options={'verbose_name': 'Administrative Staff', 'verbose_name_plural': 'Administrative Staff'},
        ),
        migrations.AlterModelOptions(
            name='magazine',
            options={},
        ),
        migrations.AlterField(
            model_name='magazine',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='magazines/pdfs/'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
