# Generated by Django 5.2.1 on 2025-06-28 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', upload_to='staff_photos/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.staffprofile')),
            ],
        ),
    ]
