# Generated by Django 5.2.1 on 2025-06-12 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_academicmenu_delete_academiccalendar_delete_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(choices=[('Faculty', 'Faculty'), ('Gallery', 'Gallery'), ('Syllabus', 'Syllabus'), ('Achievements', 'Achievements'), ('Association', 'Association'), ('Intercollege Meet', 'Intercollege Meet')], max_length=50)),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='department_sections/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='homepage.department')),
            ],
        ),
    ]
