# Generated by Django 5.2.1 on 2025-07-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_staffprofile_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField()),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (0,1,2 …)')),
            ],
            options={
                'verbose_name': 'Homepage Counter',
                'verbose_name_plural': 'Homepage Counters',
                'ordering': ['order'],
            },
        ),
    ]
