# Generated by Django 5.2.1 on 2025-06-12 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_department_departmentsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='department_images/'),
        ),
        migrations.AlterField(
            model_name='departmentsection',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departmentsection',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.department'),
        ),
        migrations.AlterField(
            model_name='departmentsection',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='department_files/'),
        ),
        migrations.AlterField(
            model_name='departmentsection',
            name='section_name',
            field=models.CharField(max_length=100),
        ),
    ]
