# Generated by Django 5.2.1 on 2025-07-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_statcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='StatCounter',
        ),
    ]
