# Generated by Django 5.2.1 on 2025-07-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_achievement_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time_to',
        ),
        migrations.AddField(
            model_name='event',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='event_pdfs/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='No description available'),
            preserve_default=False,
        ),
    ]
