# Generated by Django 5.2.1 on 2025-06-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_departmentsection_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentsection',
            name='section_name',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('gallery', 'Gallery'), ('syllabus', 'Syllabus'), ('achievements', 'Achievements'), ('association', 'Association'), ('intercollegemeet', 'Intercollege Meet')], max_length=100),
        ),
    ]
