# Generated by Django 5.2.1 on 2025-07-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_remove_event_date_to_remove_event_time_to_event_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time_from',
        ),
    ]
