# Generated by Django 5.2.1 on 2025-06-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_sliderimage_remove_homepagecontent_main_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderImage',
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_images/'),
        ),
    ]
