# Generated by Django 5.2.1 on 2025-07-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_department_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccontentblock',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academiccontentblock',
            name='table_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
