# Generated by Django 5.2.1 on 2025-07-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_academiccontentblock_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentcontent',
            name='section',
            field=models.CharField(choices=[('about', 'About'), ('faculty', 'Faculty'), ('association', 'Association'), ('syllabus', 'Syllabus'), ('gallery', 'Gallery'), ('achievements', 'Achievements'), ('intercollege', 'Intercollege Meet'), ('vision', 'Vision Mission')], max_length=50),
        ),
    ]
