# Generated by Django 5.2.1 on 2025-06-13 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_delete_sliderimage_homepagecontent_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDeskMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDeskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=300)),
                ('content', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='student_desk/files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_desk/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='student_desk/videos/')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.studentdeskmenu')),
            ],
        ),
    ]
