# Generated by Django 5.2.1 on 2025-07-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_studentlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegevideo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='collegevideo',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='collegevideo',
            name='video_link',
        ),
        migrations.AddField(
            model_name='collegevideo',
            name='video',
            field=models.FileField(default='please enter the default value now:', upload_to='videos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collegevideo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
