# Generated by Django 5.2.1 on 2025-07-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_alter_departmentcontent_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentcontent',
            name='table_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
