# Generated by Django 5.2.1 on 2025-06-13 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_naacsubmenu_naaccontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDeskSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(choices=[('examination', 'Examination'), ('code_of_conduct', 'Code of Conduct'), ('rank_holders', 'Rank Holders'), ('scholarships', 'Scholarships'), ('endowment_awards', 'Endowment & Cash Awards'), ('forms', 'Forms')], max_length=50)),
                ('heading', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='studentdesk/files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='studentdesk/images/')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.studentdeskmenu')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentDeskItem',
        ),
    ]
