# Generated by Django 5.2.3 on 2025-07-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_remove_collegevideo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
