# Generated by Django 5.2.1 on 2025-07-14 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_departmentcontent_table_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='homepage.activitycategory')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ActivityContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('table_html', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='activities/pdfs/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='homepage.activitysubsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
