# Generated by Django 5.2.1 on 2025-07-14 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_activitycategory_activitysubsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='faculty/photos/')),
                ('cv_pdf', models.FileField(blank=True, null=True, upload_to='faculty/cv/')),
                ('position', models.CharField(blank=True, max_length=200)),
                ('qualifications', models.CharField(blank=True, max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.department')),
            ],
        ),
    ]
