# Generated by Django 5.2.3 on 2025-07-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_alter_facultymember_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollegeVideo',
        ),
        migrations.RemoveField(
            model_name='homequicklink',
            name='link',
        ),
        migrations.AddField(
            model_name='achievement',
            name='date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='achievements_pdfs/'),
        ),
        migrations.AddField(
            model_name='homequicklink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homequicklink',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homequicklink',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='quick_links/pdfs/'),
        ),
        migrations.AddField(
            model_name='homequicklink',
            name='section',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homequicklink',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='quick_links/videos/'),
        ),
        migrations.AddField(
            model_name='news',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='news_pdfs/'),
        ),
        migrations.AlterField(
            model_name='homequicklink',
            name='icon',
            field=models.CharField(blank=True, help_text="Use Bootstrap icon class, e.g., 'bi-file-earmark-pdf'", max_length=100),
        ),
        migrations.AlterField(
            model_name='homequicklink',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
