# Generated by Django 5.2.1 on 2025-07-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_alter_facultymember_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='date',
            field=models.DateField(auto_now_add=True, default='2024-1-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='achievement_images/'),
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='news_pdfs/'),
        ),
    ]
