# Generated by Django 5.2.1 on 2025-06-13 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_studentdesksection_delete_studentdeskitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesMainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ActivitiesSubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('main_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='homepage.activitiesmainmenu')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitiesSubSubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubmenus', to='homepage.activitiessubmenu')),
            ],
        ),
    ]
