# Generated by Django 5.2.1 on 2025-06-13 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_activitiesmainmenu_activitiessubmenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdeskmenu',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='StudentDeskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='studentdesk/files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='studentdesk/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='studentdesk/videos/')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.studentdeskmenu')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentDeskSection',
        ),
    ]
