# Generated by Django 5.2.1 on 2025-07-14 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_facultymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('UG', 'UG'), ('PG', 'PG')], default='UG', max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('eligibility', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, help_text='Which department takes care of this course?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.department')),
            ],
            options={
                'ordering': ['level', 'order'],
            },
        ),
    ]
