# Generated by Django 5.2.3 on 2025-07-21 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_delete_collegevideo_remove_homequicklink_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IQACSubmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='naacsubmenu',
            name='title',
        ),
        migrations.AddField(
            model_name='naacsubmenu',
            name='name',
            field=models.CharField(default='Untitled', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naacsubmenu',
            name='pdf',
            field=models.FileField(default='Untitled', upload_to='naac_documents/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='IQACContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='iqac/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='iqac/pdfs/')),
                ('table_html', models.TextField(blank=True)),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.iqacsubmenu')),
            ],
        ),
        migrations.DeleteModel(
            name='NAACContentBlock',
        ),
    ]
