# Generated by Django 5.2.1 on 2025-07-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('paper', models.CharField(default='Part III (Major)', max_length=100)),
                ('rank', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='rankholders/')),
            ],
        ),
    ]
