# Generated by Django 5.2.1 on 2025-06-13 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_alter_studentdeskmenu_slug_studentdeskitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicmenu',
            name='content',
        ),
        migrations.RemoveField(
            model_name='academicmenu',
            name='image',
        ),
        migrations.RemoveField(
            model_name='academicmenu',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='academicmenu',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='AcademicSubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.academicmenu')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='academic/')),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.academicsubmenu')),
            ],
        ),
    ]
