# Generated by Django 5.2.3 on 2025-07-23 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_grievance_grievancecommitteemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='committee_content/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='committee_pdfs/')),
                ('table_html', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='committee_units/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Grievance',
        ),
        migrations.DeleteModel(
            name='GrievanceCommitteeMember',
        ),
        migrations.AddField(
            model_name='committeecontentblock',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='homepage.committeesection'),
        ),
        migrations.AddField(
            model_name='committeesection',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='homepage.committeeunit'),
        ),
    ]
