# Generated by Django 5.2.1 on 2025-06-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_remove_academicmenu_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='extension/')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ICCSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='icc/')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IICSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='iic/')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OtherActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='other/')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SportsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sports/')),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='activitiessubmenu',
            name='main_menu',
        ),
        migrations.RemoveField(
            model_name='activitiessubsubmenu',
            name='submenu',
        ),
        migrations.DeleteModel(
            name='ActivitiesMainMenu',
        ),
        migrations.DeleteModel(
            name='ActivitiesSubMenu',
        ),
        migrations.DeleteModel(
            name='ActivitiesSubSubMenu',
        ),
    ]
