# Generated by Django 5.2.1 on 2025-07-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_rankholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndowmentPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('founder', models.CharField(max_length=255)),
                ('memory_of', models.CharField(max_length=255)),
                ('awarded_to', models.TextField()),
                ('amount', models.CharField(max_length=50)),
            ],
        ),
    ]
