# Generated by Django 5.2.1 on 2025-06-14 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_extensionactivity_iccsection_iicsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('has_submenu', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'activity_section',
            },
        ),
        migrations.CreateModel(
            name='ActivitySubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='activities/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='homepage.activitysection')),
            ],
            options={
                'db_table': 'activity_subsection',
            },
        ),
        migrations.DeleteModel(
            name='ExtensionActivity',
        ),
        migrations.DeleteModel(
            name='ICCSection',
        ),
        migrations.DeleteModel(
            name='IICSection',
        ),
        migrations.DeleteModel(
            name='OtherActivity',
        ),
        migrations.DeleteModel(
            name='SportsSection',
        ),
    ]
