# Generated by Django 5.2.1 on 2025-07-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_endowmentprize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='studentdesk/forms/')),
            ],
        ),
    ]
