# Generated by Django 5.2.1 on 2025-06-14 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_activitysection_activitysubsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('table_html', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='about/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='AboutSubmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutMenu',
        ),
        migrations.AddField(
            model_name='aboutcontentblock',
            name='submenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='homepage.aboutsubmenu'),
        ),
    ]
