# Generated by Django 5.2.1 on 2025-06-14 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_aboutcontentblock_aboutsubmenu_delete_aboutmenu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutcontentblock',
            old_name='table_html',
            new_name='table',
        ),
    ]
