# Generated by Django 5.2.1 on 2025-06-14 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_rename_table_html_aboutcontentblock_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentsection',
            name='department',
        ),
        migrations.RemoveField(
            model_name='academicmenu',
            name='slug',
        ),
        migrations.AlterField(
            model_name='academicsubmenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='homepage.academicmenu'),
        ),
        migrations.CreateModel(
            name='AcademicContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='academic/images/')),
                ('content', models.TextField(blank=True, null=True)),
                ('table_html', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='academic/files/')),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='homepage.academicsubmenu')),
            ],
        ),
        migrations.DeleteModel(
            name='AcademicContent',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='DepartmentSection',
        ),
    ]
