# Generated by Django 5.2.1 on 2025-06-14 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_remove_departmentsection_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('block_content', models.TextField(blank=True)),
                ('table_content', models.TextField(blank=True, help_text='Paste valid HTML table code.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='departments/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='departments/pdfs/')),
            ],
        ),
        migrations.RemoveField(
            model_name='academicsubmenu',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='activitysubsection',
            name='section',
        ),
        migrations.AlterModelOptions(
            name='activitysection',
            options={'ordering': ['order', 'name']},
        ),
        migrations.RemoveField(
            model_name='activitysection',
            name='has_submenu',
        ),
        migrations.AddField(
            model_name='academicsubmenu',
            name='block_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='academicsubmenu',
            name='heading',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='academicsubmenu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='academic_submenu/images/'),
        ),
        migrations.AddField(
            model_name='academicsubmenu',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='academic_submenu/pdfs/'),
        ),
        migrations.AddField(
            model_name='academicsubmenu',
            name='table_content',
            field=models.TextField(blank=True, help_text='Paste valid HTML table code.'),
        ),
        migrations.AddField(
            model_name='activitysection',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activitysection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='homepage.activitysection'),
        ),
        migrations.AlterField(
            model_name='academicsubmenu',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='academicsubmenu',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activitysection',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='activitysection',
            table=None,
        ),
        migrations.CreateModel(
            name='ActivityContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('block', models.TextField(blank=True)),
                ('table', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='activity_pdfs/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='homepage.activitysection')),
            ],
        ),
        migrations.DeleteModel(
            name='AcademicContentBlock',
        ),
        migrations.DeleteModel(
            name='AcademicMenu',
        ),
        migrations.DeleteModel(
            name='ActivitySubSection',
        ),
    ]
