# Generated by Django 5.2.1 on 2025-06-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_department_remove_academicsubmenu_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty_details',
            field=models.TextField(blank=True),
        ),
    ]
