# Generated by Django 5.2.1 on 2025-06-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_department_achievements_department_faculty_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsubmenu',
            name='gallery_images',
            field=models.ImageField(blank=True, null=True, upload_to='department_gallery/'),
        ),
    ]
