# Generated by Django 5.2.1 on 2025-06-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_academicsubmenu_gallery_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='gallery_images',
            field=models.ImageField(blank=True, null=True, upload_to='department_gallery/'),
        ),
    ]
