# Generated by Django 5.2.1 on 2025-06-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0027_department_gallery_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcontentblock',
            name='table',
        ),
        migrations.AddField(
            model_name='aboutcontentblock',
            name='table_content',
            field=models.TextField(blank=True, help_text='Paste valid HTML table code.'),
        ),
    ]
