# Generated by Django 5.2.1 on 2025-06-14 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0028_remove_aboutcontentblock_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDeskContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('table_html', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='studentdesk/files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='studentdesk/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='studentdesk/videos/')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='homepage.studentdeskmenu')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentDeskItem',
        ),
    ]
