# Generated by Django 5.2.1 on 2025-06-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0029_studentdeskcontentblock_delete_studentdeskitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitycontent',
            name='table',
        ),
        migrations.AddField(
            model_name='activitycontent',
            name='table_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
