# Generated by Django 5.2.1 on 2025-06-15 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0030_remove_activitycontent_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcontentblock',
            name='table_content',
        ),
        migrations.RemoveField(
            model_name='academicsubmenu',
            name='block_content',
        ),
        migrations.RemoveField(
            model_name='academicsubmenu',
            name='gallery_images',
        ),
        migrations.RemoveField(
            model_name='academicsubmenu',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='academicsubmenu',
            name='image',
        ),
        migrations.RemoveField(
            model_name='academicsubmenu',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='academicsubmenu',
            name='table_content',
        ),
        migrations.RemoveField(
            model_name='department',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='department',
            name='block_content',
        ),
        migrations.RemoveField(
            model_name='department',
            name='faculty_details',
        ),
        migrations.RemoveField(
            model_name='department',
            name='gallery_images',
        ),
        migrations.RemoveField(
            model_name='department',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='department',
            name='image',
        ),
        migrations.RemoveField(
            model_name='department',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='department',
            name='table_content',
        ),
        migrations.AddField(
            model_name='aboutcontentblock',
            name='table_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicsubmenu',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academicsubmenu',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='academicsubmenu',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='AcademicContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='academic/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='academic/pdfs/')),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.academicsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('about', 'About'), ('faculty', 'Faculty'), ('association', 'Association'), ('syllabus', 'Syllabus'), ('gallery', 'Gallery'), ('achievements', 'Achievements'), ('intercollege', 'Intercollege Meet')], max_length=50)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='departments/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='departments/pdfs/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.department')),
            ],
        ),
    ]
