# Generated by Django 5.2.1 on 2025-06-15 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0031_remove_aboutcontentblock_table_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='naacsubmenu',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='NAACContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='naac/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='naac/pdfs/')),
                ('table_html', models.TextField(blank=True, help_text='Paste HTML table code if needed.', null=True)),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='homepage.naacsubmenu')),
            ],
        ),
        migrations.DeleteModel(
            name='NAACContent',
        ),
    ]
