# Generated by Django 5.2.1 on 2025-06-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0033_alter_naacsubmenu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naacsubmenu',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
