# Generated by Django 5.2.1 on 2025-06-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0034_alter_naacsubmenu_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naacsubmenu',
            name='slug',
        ),
        migrations.AlterField(
            model_name='naaccontentblock',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='naaccontentblock',
            name='table_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
