# Generated by Django 5.2.1 on 2025-06-19 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0035_remove_naacsubmenu_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='naaccontentblock',
            name='date',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='naaccontentblock',
            name='content',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='naaccontentblock',
            name='heading',
            field=models.CharField(blank=True, default='2025-8-12', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='naaccontentblock',
            name='submenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.naacsubmenu'),
        ),
        migrations.AlterField(
            model_name='naaccontentblock',
            name='table_html',
            field=models.TextField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
