# Generated by Django 5.2.1 on 2025-06-19 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0036_naaccontentblock_date_alter_naaccontentblock_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naaccontentblock',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
