# Generated by Django 5.2.1 on 2025-06-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0037_alter_naaccontentblock_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naaccontentblock',
            name='date',
        ),
    ]
